export const Types = {
    TYPE:'TYPE',
    LOGIN_USER:'LOGIN_USER',
    GET_CATEGORY:'GET_CATEGORY',
    ERROR_CATEGORY:'ERROR_CATEGORY',

    GET_PRODUCT:'GET_PRODUCT',
    SET_PRODUCT:'SET_PRODUCT',
    ERROR_PRODUCT:'ERROR_PRODUCT'
}

